export const meetingRooms = [
  'Phòng họp số 01',
  'Phòng họp số 02',
  'Phòng họp lớn',
  'Phòng trực tuyến',
]

export const meetingHosts = ['Nguyễn Văn A', 'Trần Văn B', 'Lê Văn C', 'Phạm Thị D']

export const meetingTypes = [
  { id: 'giao-ban', label: 'Họp giao ban', color: 'green' },
  { id: 'hdnd', label: 'Họp HĐND', color: 'blue' },
  { id: 'noi-bo', label: 'Họp nội bộ', color: 'orange' },
  { id: 'khan', label: 'Khẩn', color: 'red' },
  { id: 'chuyen-de', label: 'Họp chuyên đề', color: 'purple' },
]

export const meetingStatuses = ['Chưa bắt đầu', 'Đang diễn ra', 'Đã kết thúc', 'Đã huỷ']

const defaultOptions = {
  attendance: 'QR Code',
  recording: false,
  reminders: ['Trước 30 phút', 'Trước 1 giờ'],
  voting: true,
}

export const calendarMeetings = [
  {
    id: 1,
    title: 'Họp giao ban đầu tuần',
    description: 'Trao đổi tình hình hoạt động trong tuần và phân công nhiệm vụ trọng tâm.',
    date: '2026-07-15',
    startTime: '08:00',
    endTime: '09:30',
    allDay: false,
    meetingMode: 'Trực tiếp',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    type: 'giao-ban',
    status: 'Đang diễn ra',
    departments: ['Văn phòng', 'Công an', 'Nội vụ'],
    guests: [
      {
        name: 'Nguyễn Văn B',
        unit: 'UBND xã',
        email: 'nguyenvanb@donvi.gov.vn',
        phone: '0900 000 001',
      },
    ],
    participants: ['UBND xã', 'Công an xã', 'Ban chỉ huy quân sự', 'Văn phòng'],
    documents: ['Kế hoạch.pdf', 'Báo cáo.docx', 'Chương trình.xlsx'],
    minutesStatus: 'Đã cập nhật',
    options: { ...defaultOptions, recording: true },
  },
  {
    id: 2,
    title: 'Họp HĐND chuyên đề',
    description: 'Thảo luận nội dung trình kỳ họp HĐND và rà soát dự thảo nghị quyết.',
    date: '2026-07-15',
    startTime: '09:30',
    endTime: '11:00',
    allDay: false,
    meetingMode: 'Kết hợp',
    room: 'Phòng họp số 02',
    host: 'Trần Văn B',
    type: 'hdnd',
    status: 'Sắp diễn ra',
    departments: ['Văn phòng', 'Tài chính'],
    guests: [],
    participants: ['Thường trực HĐND', 'UBND xã', 'Mặt trận Tổ quốc'],
    documents: ['Tờ trình.pdf', 'Dự thảo nghị quyết.docx'],
    minutesStatus: 'Chưa có',
    options: { ...defaultOptions, attendance: 'QR + FaceID' },
  },
  {
    id: 3,
    title: 'Họp nội bộ văn phòng',
    description: 'Sắp xếp lịch trực, rà soát hồ sơ tồn và phân công bộ phận xử lý.',
    date: '2026-07-15',
    startTime: '14:00',
    endTime: '15:00',
    allDay: false,
    meetingMode: 'Trực tuyến',
    room: 'Phòng trực tuyến',
    host: 'Lê Văn C',
    type: 'noi-bo',
    status: 'Chưa bắt đầu',
    departments: ['Văn phòng', 'Nội vụ'],
    guests: [],
    participants: ['Văn phòng', 'Bộ phận một cửa'],
    documents: ['Lịch trực.xlsx'],
    minutesStatus: 'Chưa có',
    options: { ...defaultOptions, voting: false },
  },
  {
    id: 4,
    title: 'Xử lý tình huống khẩn',
    description: 'Kích hoạt phương án xử lý nhanh và thống nhất đầu mối phối hợp.',
    date: '2026-07-16',
    startTime: '10:00',
    endTime: '11:30',
    allDay: false,
    meetingMode: 'Kết hợp',
    room: 'Phòng họp lớn',
    host: 'Phạm Thị D',
    type: 'khan',
    status: 'Chưa bắt đầu',
    departments: ['Công an', 'Địa chính'],
    guests: [],
    participants: ['Công an xã', 'Trạm y tế', 'Ban chỉ huy quân sự'],
    documents: ['Phương án xử lý.pdf'],
    minutesStatus: 'Chưa có',
    options: { ...defaultOptions, attendance: 'Thủ công', recording: true },
  },
  {
    id: 5,
    title: 'Họp chuyên đề chuyển đổi số',
    description: 'Triển khai tài khoản, quy trình họp trực tuyến và lưu trữ tài liệu số.',
    date: '2026-07-17',
    startTime: '08:30',
    endTime: '10:00',
    allDay: false,
    meetingMode: 'Trực tuyến',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    type: 'chuyen-de',
    status: 'Chưa bắt đầu',
    departments: ['Văn phòng', 'Nội vụ'],
    guests: [],
    participants: ['Tổ công nghệ số', 'Văn phòng', 'Đoàn thanh niên'],
    documents: ['Kế hoạch chuyển đổi số.pdf', 'Danh sách tài khoản.xlsx'],
    minutesStatus: 'Chưa có',
    options: defaultOptions,
  },
  {
    id: 6,
    title: 'Họp giao ban an ninh',
    description: 'Báo cáo tình hình an ninh trật tự và kế hoạch tuần tới.',
    date: '2026-07-20',
    startTime: '08:00',
    endTime: '09:00',
    allDay: false,
    meetingMode: 'Trực tiếp',
    room: 'Phòng họp số 02',
    host: 'Trần Văn B',
    type: 'giao-ban',
    status: 'Chưa bắt đầu',
    departments: ['Công an'],
    guests: [],
    participants: ['Công an xã', 'Dân quân tự vệ', 'Tổ dân phố'],
    documents: ['Báo cáo an ninh.pdf'],
    minutesStatus: 'Chưa có',
    options: defaultOptions,
  },
  {
    id: 7,
    title: 'Họp HĐND thường kỳ',
    description: 'Tổ chức phiên họp thường kỳ, thảo luận báo cáo kinh tế xã hội.',
    date: '2026-07-22',
    startTime: '13:30',
    endTime: '16:00',
    allDay: false,
    meetingMode: 'Trực tiếp',
    room: 'Phòng họp lớn',
    host: 'Lê Văn C',
    type: 'hdnd',
    status: 'Chưa bắt đầu',
    departments: ['Văn phòng', 'Tài chính', 'Địa chính'],
    guests: [],
    participants: ['Đại biểu HĐND', 'UBND xã', 'Các ban ngành'],
    documents: ['Chương trình kỳ họp.pdf', 'Báo cáo kinh tế xã hội.docx'],
    minutesStatus: 'Chưa có',
    options: { ...defaultOptions, attendance: 'QR + FaceID', recording: true },
  },
  {
    id: 8,
    title: 'Rà soát hồ sơ nội bộ',
    description: 'Rà soát danh mục hồ sơ, phân loại tồn đọng và thời hạn xử lý.',
    date: '2026-07-24',
    startTime: '15:00',
    endTime: '16:30',
    allDay: false,
    meetingMode: 'Trực tuyến',
    room: 'Phòng trực tuyến',
    host: 'Phạm Thị D',
    type: 'noi-bo',
    status: 'Chưa bắt đầu',
    departments: ['Văn phòng'],
    guests: [],
    participants: ['Văn phòng', 'Tư pháp hộ tịch'],
    documents: ['Danh mục hồ sơ.xlsx'],
    minutesStatus: 'Chưa có',
    options: { ...defaultOptions, voting: false, recording: false },
  },
  {
    id: 9,
    title: 'Họp chuyên đề ngân sách',
    description: 'Thống nhất dự toán ngân sách và phương án phân bổ theo lĩnh vực.',
    date: '2026-07-28',
    startTime: '09:00',
    endTime: '10:30',
    allDay: false,
    meetingMode: 'Trực tiếp',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    type: 'chuyen-de',
    status: 'Chưa bắt đầu',
    departments: ['Tài chính', 'Văn phòng'],
    guests: [],
    participants: ['Tài chính kế toán', 'UBND xã', 'HĐND xã'],
    documents: ['Dự toán ngân sách.xlsx', 'Thuyết minh.pdf'],
    minutesStatus: 'Chưa có',
    options: defaultOptions,
  },
]
