export const meetingRooms = [
  'Phòng họp số 01',
  'Phòng họp số 02',
  'Phòng họp lớn',
  'Phòng trực tuyến',
]

export const meetingHosts = ['Nguyễn Văn A', 'Trần Văn B', 'Lê Văn C', 'Phạm Thị D']

export const meetingTypes = [
  { id: 'giao-ban', label: 'Họp giao ban', color: 'green' },
  { id: 'hdnd', label: 'Họp HĐND', color: 'blue' },
  { id: 'noi-bo', label: 'Họp nội bộ', color: 'orange' },
  { id: 'khan', label: 'Khẩn', color: 'red' },
  { id: 'chuyen-de', label: 'Họp chuyên đề', color: 'purple' },
]

export const meetingStatuses = ['Chưa bắt đầu', 'Đang diễn ra', 'Đã kết thúc', 'Đã huỷ']

export const calendarMeetings = [
  {
    id: 1,
    title: 'Họp giao ban đầu tuần',
    date: '2026-07-15',
    startTime: '08:00',
    endTime: '09:30',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    type: 'giao-ban',
    status: 'Đang diễn ra',
    participants: ['UBND xã', 'Công an xã', 'Ban chỉ huy quân sự', 'Văn phòng'],
    documents: ['Kế hoạch.pdf', 'Báo cáo.docx', 'Chương trình.xlsx'],
    minutesStatus: 'Đã cập nhật',
  },
  {
    id: 2,
    title: 'Họp HĐND chuyên đề',
    date: '2026-07-15',
    startTime: '09:30',
    endTime: '11:00',
    room: 'Phòng họp số 02',
    host: 'Trần Văn B',
    type: 'hdnd',
    status: 'Sắp diễn ra',
    participants: ['Thường trực HĐND', 'UBND xã', 'Mặt trận Tổ quốc'],
    documents: ['Tờ trình.pdf', 'Dự thảo nghị quyết.docx'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 3,
    title: 'Họp nội bộ văn phòng',
    date: '2026-07-15',
    startTime: '14:00',
    endTime: '15:00',
    room: 'Phòng trực tuyến',
    host: 'Lê Văn C',
    type: 'noi-bo',
    status: 'Chưa bắt đầu',
    participants: ['Văn phòng', 'Bộ phận một cửa'],
    documents: ['Lịch trực.xlsx'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 4,
    title: 'Xử lý tình huống khẩn',
    date: '2026-07-16',
    startTime: '10:00',
    endTime: '11:30',
    room: 'Phòng họp lớn',
    host: 'Phạm Thị D',
    type: 'khan',
    status: 'Chưa bắt đầu',
    participants: ['Công an xã', 'Trạm y tế', 'Ban chỉ huy quân sự'],
    documents: ['Phương án xử lý.pdf'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 5,
    title: 'Họp chuyên đề chuyển đổi số',
    date: '2026-07-17',
    startTime: '08:30',
    endTime: '10:00',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    type: 'chuyen-de',
    status: 'Chưa bắt đầu',
    participants: ['Tổ công nghệ số', 'Văn phòng', 'Đoàn thanh niên'],
    documents: ['Kế hoạch chuyển đổi số.pdf', 'Danh sách tài khoản.xlsx'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 6,
    title: 'Họp giao ban an ninh',
    date: '2026-07-20',
    startTime: '08:00',
    endTime: '09:00',
    room: 'Phòng họp số 02',
    host: 'Trần Văn B',
    type: 'giao-ban',
    status: 'Chưa bắt đầu',
    participants: ['Công an xã', 'Dân quân tự vệ', 'Tổ dân phố'],
    documents: ['Báo cáo an ninh.pdf'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 7,
    title: 'Họp HĐND thường kỳ',
    date: '2026-07-22',
    startTime: '13:30',
    endTime: '16:00',
    room: 'Phòng họp lớn',
    host: 'Lê Văn C',
    type: 'hdnd',
    status: 'Chưa bắt đầu',
    participants: ['Đại biểu HĐND', 'UBND xã', 'Các ban ngành'],
    documents: ['Chương trình kỳ họp.pdf', 'Báo cáo kinh tế xã hội.docx'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 8,
    title: 'Rà soát hồ sơ nội bộ',
    date: '2026-07-24',
    startTime: '15:00',
    endTime: '16:30',
    room: 'Phòng trực tuyến',
    host: 'Phạm Thị D',
    type: 'noi-bo',
    status: 'Chưa bắt đầu',
    participants: ['Văn phòng', 'Tư pháp hộ tịch'],
    documents: ['Danh mục hồ sơ.xlsx'],
    minutesStatus: 'Chưa có',
  },
  {
    id: 9,
    title: 'Họp chuyên đề ngân sách',
    date: '2026-07-28',
    startTime: '09:00',
    endTime: '10:30',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    type: 'chuyen-de',
    status: 'Chưa bắt đầu',
    participants: ['Tài chính kế toán', 'UBND xã', 'HĐND xã'],
    documents: ['Dự toán ngân sách.xlsx', 'Thuyết minh.pdf'],
    minutesStatus: 'Chưa có',
  },
]
