export const deviceCategories = [
  'Camera họp',
  'Webcam',
  'Micro',
  'Loa',
  'Máy chiếu',
  'TV',
  'Màn hình LED',
  'Máy tính',
  'Laptop',
  'Bộ điều khiển',
  'Thiết bị hội nghị',
  'Bộ định tuyến',
  'Switch mạng',
  'WiFi',
  'UPS',
  'Điều hòa',
  'Máy in',
  'Bảng điện tử',
]

export const deviceStatuses = ['Đang hoạt động', 'Đang bảo trì', 'Hỏng', 'Dự phòng']

export const devicesData = [
  { id: 1, name: 'Camera Logitech Rally', code: 'CAM001', category: 'Camera họp', brand: 'Logitech', model: 'Rally', quantity: 2, location: 'Kho tầng 2', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: 'Dùng cho phòng họp lớn' },
  { id: 2, name: 'Camera Hikvision PTZ', code: 'CAM002', category: 'Camera họp', brand: 'Hikvision', model: 'DS-2DE', quantity: 1, location: 'Phòng họp số 01', status: 'Đang hoạt động', updatedAt: '17/07/2026', note: 'Gắn trần' },
  { id: 3, name: 'Webcam Logitech Brio', code: 'WEB001', category: 'Webcam', brand: 'Logitech', model: 'Brio 4K', quantity: 4, location: 'Kho tầng 2', status: 'Đang hoạt động', updatedAt: '15/07/2026', note: '' },
  { id: 4, name: 'Webcam Microsoft LifeCam', code: 'WEB002', category: 'Webcam', brand: 'Microsoft', model: 'LifeCam Studio', quantity: 3, location: 'Kho tầng 2', status: 'Dự phòng', updatedAt: '12/07/2026', note: '' },
  { id: 5, name: 'Micro không dây Shure', code: 'MIC001', category: 'Micro', brand: 'Shure', model: 'BLX24', quantity: 6, location: 'Kho âm thanh', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 6, name: 'Micro cổ ngỗng TOA', code: 'MIC002', category: 'Micro', brand: 'TOA', model: 'TS-681L', quantity: 12, location: 'Phòng họp lớn', status: 'Đang hoạt động', updatedAt: '14/07/2026', note: '' },
  { id: 7, name: 'Micro hội nghị Bosch', code: 'MIC003', category: 'Micro', brand: 'Bosch', model: 'CCS 1000D', quantity: 10, location: 'Tủ thiết bị phòng họp số 02', status: 'Đang bảo trì', updatedAt: '11/07/2026', note: 'Kiểm tra dây kết nối' },
  { id: 8, name: 'Loa hội nghị Jabra Speak', code: 'SPK001', category: 'Loa', brand: 'Jabra', model: 'Speak 750', quantity: 5, location: 'Kho tầng 2', status: 'Đang hoạt động', updatedAt: '17/07/2026', note: '' },
  { id: 9, name: 'Loa âm trần TOA', code: 'SPK002', category: 'Loa', brand: 'TOA', model: 'PC-658R', quantity: 8, location: 'Phòng họp lớn', status: 'Đang hoạt động', updatedAt: '10/07/2026', note: '' },
  { id: 10, name: 'Máy chiếu Epson EB-X51', code: 'PRJ001', category: 'Máy chiếu', brand: 'Epson', model: 'EB-X51', quantity: 2, location: 'Kho tầng 2', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 11, name: 'Máy chiếu Panasonic PT-VZ580', code: 'PRJ002', category: 'Máy chiếu', brand: 'Panasonic', model: 'PT-VZ580', quantity: 1, location: 'Hội trường trung tâm', status: 'Đang hoạt động', updatedAt: '16/07/2026', note: '' },
  { id: 12, name: 'Smart TV Samsung 75"', code: 'TV001', category: 'TV', brand: 'Samsung', model: 'UA75AU8000', quantity: 2, location: 'Phòng họp số 01', status: 'Đang hoạt động', updatedAt: '13/07/2026', note: '' },
  { id: 13, name: 'Smart TV LG 65"', code: 'TV002', category: 'TV', brand: 'LG', model: '65UQ8050', quantity: 2, location: 'Phòng họp A', status: 'Đang hoạt động', updatedAt: '09/07/2026', note: '' },
  { id: 14, name: 'Màn hình LED P2.5', code: 'LED001', category: 'Màn hình LED', brand: 'Absen', model: 'P2.5', quantity: 1, location: 'Hội trường trung tâm', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 15, name: 'Màn hình Dell 27"', code: 'MON001', category: 'Màn hình LED', brand: 'Dell', model: 'P2722H', quantity: 6, location: 'Kho CNTT', status: 'Dự phòng', updatedAt: '08/07/2026', note: '' },
  { id: 16, name: 'Máy tính Dell OptiPlex', code: 'PC001', category: 'Máy tính', brand: 'Dell', model: 'OptiPlex 3090', quantity: 5, location: 'Kho CNTT', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 17, name: 'Máy tính HP ProDesk', code: 'PC002', category: 'Máy tính', brand: 'HP', model: 'ProDesk 400', quantity: 4, location: 'Kho CNTT', status: 'Đang hoạt động', updatedAt: '07/07/2026', note: '' },
  { id: 18, name: 'Laptop Dell Latitude', code: 'LAP001', category: 'Laptop', brand: 'Dell', model: 'Latitude 5420', quantity: 3, location: 'Văn phòng UBND', status: 'Đang hoạt động', updatedAt: '15/07/2026', note: '' },
  { id: 19, name: 'Laptop Lenovo ThinkPad', code: 'LAP002', category: 'Laptop', brand: 'Lenovo', model: 'ThinkPad E14', quantity: 2, location: 'Kho CNTT', status: 'Dự phòng', updatedAt: '05/07/2026', note: '' },
  { id: 20, name: 'Bộ điều khiển trung tâm Crestron', code: 'CTL001', category: 'Bộ điều khiển', brand: 'Crestron', model: 'CP4', quantity: 1, location: 'Phòng họp lớn', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 21, name: 'Bộ điều khiển Kramer', code: 'CTL002', category: 'Bộ điều khiển', brand: 'Kramer', model: 'SL-240C', quantity: 1, location: 'Phòng trực tuyến', status: 'Đang bảo trì', updatedAt: '12/07/2026', note: '' },
  { id: 22, name: 'Thiết bị hội nghị Poly Studio', code: 'VC001', category: 'Thiết bị hội nghị', brand: 'Poly', model: 'Studio X50', quantity: 2, location: 'Phòng họp số 02', status: 'Đang hoạt động', updatedAt: '16/07/2026', note: '' },
  { id: 23, name: 'Thiết bị hội nghị Cisco Webex', code: 'VC002', category: 'Thiết bị hội nghị', brand: 'Cisco', model: 'Room Kit Mini', quantity: 1, location: 'Phòng trực tuyến', status: 'Đang hoạt động', updatedAt: '17/07/2026', note: '' },
  { id: 24, name: 'Router WiFi MikroTik', code: 'RTR001', category: 'Bộ định tuyến', brand: 'MikroTik', model: 'RB4011', quantity: 2, location: 'Tủ mạng tầng 2', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 25, name: 'Router Cisco ISR', code: 'RTR002', category: 'Bộ định tuyến', brand: 'Cisco', model: 'ISR 1100', quantity: 1, location: 'Phòng server', status: 'Đang hoạt động', updatedAt: '09/07/2026', note: '' },
  { id: 26, name: 'Switch mạng TP-Link 24 Port', code: 'SW001', category: 'Switch mạng', brand: 'TP-Link', model: 'TL-SG1024', quantity: 3, location: 'Tủ mạng tầng 2', status: 'Đang hoạt động', updatedAt: '13/07/2026', note: '' },
  { id: 27, name: 'Switch Cisco Catalyst', code: 'SW002', category: 'Switch mạng', brand: 'Cisco', model: 'C1000-24T', quantity: 1, location: 'Phòng server', status: 'Đang hoạt động', updatedAt: '11/07/2026', note: '' },
  { id: 28, name: 'Access Point UniFi 6', code: 'WIFI001', category: 'WiFi', brand: 'Ubiquiti', model: 'U6 Lite', quantity: 6, location: 'Trần hành lang', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 29, name: 'Access Point Aruba', code: 'WIFI002', category: 'WiFi', brand: 'Aruba', model: 'AP22', quantity: 3, location: 'Kho CNTT', status: 'Dự phòng', updatedAt: '04/07/2026', note: '' },
  { id: 30, name: 'UPS APC 1500VA', code: 'UPS001', category: 'UPS', brand: 'APC', model: 'BX1500M', quantity: 4, location: 'Tủ thiết bị', status: 'Đang hoạt động', updatedAt: '18/07/2026', note: '' },
  { id: 31, name: 'UPS Santak 1000VA', code: 'UPS002', category: 'UPS', brand: 'Santak', model: 'TG1000', quantity: 2, location: 'Kho tầng 1', status: 'Hỏng', updatedAt: '06/07/2026', note: 'Chờ thay ắc quy' },
  { id: 32, name: 'Điều hòa Daikin 24000BTU', code: 'AC001', category: 'Điều hòa', brand: 'Daikin', model: 'FTKC60', quantity: 3, location: 'Phòng họp lớn', status: 'Đang hoạt động', updatedAt: '14/07/2026', note: '' },
  { id: 33, name: 'Điều hòa Panasonic 18000BTU', code: 'AC002', category: 'Điều hòa', brand: 'Panasonic', model: 'CU/CS', quantity: 2, location: 'Phòng họp B', status: 'Đang bảo trì', updatedAt: '10/07/2026', note: '' },
  { id: 34, name: 'Máy in HP LaserJet', code: 'PRN001', category: 'Máy in', brand: 'HP', model: 'M404dn', quantity: 2, location: 'Văn phòng UBND', status: 'Đang hoạt động', updatedAt: '17/07/2026', note: '' },
  { id: 35, name: 'Máy in Canon LBP', code: 'PRN002', category: 'Máy in', brand: 'Canon', model: 'LBP 2900', quantity: 4, location: 'Kho tầng 1', status: 'Dự phòng', updatedAt: '03/07/2026', note: '' },
  { id: 36, name: 'Bảng điện tử Samsung Flip', code: 'BOARD001', category: 'Bảng điện tử', brand: 'Samsung', model: 'Flip 2', quantity: 1, location: 'Phòng họp A', status: 'Đang hoạt động', updatedAt: '16/07/2026', note: '' },
]

export const getDeviceDisplayName = (device) => device?.name || ''
