export const meetingRooms = [
  {
    id: 'meeting-001',
    title: 'Họp giao ban đầu tuần',
    room: 'Phòng họp số 01',
    host: 'Nguyễn Văn A',
    time: '08:00 - 09:30',
    status: 'Đang diễn ra',
    participants: [
      { id: 'p1', name: 'Nguyễn Văn A', role: 'Chủ trì', active: true },
      { id: 'p2', name: 'Trần Văn B', role: 'Đại biểu', active: true },
      { id: 'p3', name: 'Lê Văn C', role: 'Đại biểu', active: true },
      { id: 'p4', name: 'Phạm Thị D', role: 'Văn phòng', active: false },
      { id: 'p5', name: 'Công an xã', role: 'Đơn vị', active: true },
      { id: 'p6', name: 'Ban CHQS', role: 'Đơn vị', active: true },
    ],
    documents: ['Kế hoạch.pdf', 'Báo cáo.docx', 'Chương trình.xlsx'],
    messages: [
      { id: 1, sender: 'Văn phòng', content: 'Tài liệu đã được cập nhật.', time: '08:02' },
      { id: 2, sender: 'Nguyễn Văn A', content: 'Mời các đơn vị báo cáo nhanh.', time: '08:05' },
    ],
  },
  {
    id: 'meeting-002',
    title: 'Họp HĐND chuyên đề',
    room: 'Phòng họp số 02',
    host: 'Trần Văn B',
    time: '09:30 - 11:00',
    status: 'Sắp diễn ra',
    participants: [
      { id: 'p1', name: 'Trần Văn B', role: 'Chủ trì', active: true },
      { id: 'p2', name: 'Thường trực HĐND', role: 'Đại biểu', active: true },
      { id: 'p3', name: 'UBND xã', role: 'Đơn vị', active: false },
    ],
    documents: ['Tờ trình.pdf', 'Dự thảo nghị quyết.docx'],
    messages: [],
  },
  {
    id: 'meeting-003',
    title: 'Họp nội bộ văn phòng',
    room: 'Phòng trực tuyến',
    host: 'Lê Văn C',
    time: '14:00 - 15:00',
    status: 'Chưa bắt đầu',
    participants: [
      { id: 'p1', name: 'Lê Văn C', role: 'Chủ trì', active: true },
      { id: 'p2', name: 'Bộ phận một cửa', role: 'Đơn vị', active: true },
      { id: 'p3', name: 'Văn phòng', role: 'Đơn vị', active: true },
    ],
    documents: ['Lịch trực.xlsx'],
    messages: [],
  },
  {
    id: 'meeting-004',
    title: 'Xử lý tình huống khẩn',
    room: 'Phòng họp lớn',
    host: 'Phạm Thị D',
    time: '10:00 - 11:30',
    status: 'Chưa bắt đầu',
    participants: [
      { id: 'p1', name: 'Phạm Thị D', role: 'Chủ trì', active: true },
      { id: 'p2', name: 'Công an xã', role: 'Đơn vị', active: true },
      { id: 'p3', name: 'Trạm y tế', role: 'Đơn vị', active: false },
    ],
    documents: ['Phương án xử lý.pdf'],
    messages: [],
  },
  {
    id: 'meeting-005',
    title: 'Họp trực tuyến chuyên đề',
    room: 'Phòng họp lớn',
    host: 'Phạm Thị D',
    time: '08:30 - 10:00',
    status: 'Đang diễn ra',
    participants: [
      { id: 'p1', name: 'Phạm Thị D', role: 'Chủ trì', active: true },
      { id: 'p2', name: 'Tổ công nghệ số', role: 'Đơn vị', active: true },
      { id: 'p3', name: 'Văn phòng', role: 'Đơn vị', active: true },
      { id: 'p4', name: 'Đoàn thanh niên', role: 'Đơn vị', active: false },
    ],
    documents: ['Kế hoạch chuyển đổi số.pdf', 'Danh sách tài khoản.xlsx'],
    messages: [
      { id: 1, sender: 'Tổ công nghệ số', content: 'Đã sẵn sàng trình chiếu.', time: '08:31' },
    ],
  },
]

export const fallbackMeetingRoom = meetingRooms[0]
