export const documentCategories = ['Tất cả', 'Agenda', 'Quyết định', 'Báo cáo', 'PowerPoint', 'Biên bản', 'Video', 'Khác']

export const documentTypes = ['PDF', 'DOCX', 'XLSX', 'PPTX', 'MP4', 'JPG', 'PNG', 'ZIP']

export const meetingDocuments = [
  { id: 1, name: 'Agenda.pdf', category: 'Agenda', type: 'PDF', size: '1.2 MB', uploader: 'Nguyễn Văn A', uploadDate: '10/07/2026', updatedAt: '15/07/2026', version: 'v2.0', description: 'Chương trình họp giao ban UBND xã tháng 07/2026.', note: 'Đã cập nhật thứ tự nội dung trình bày.' },
  { id: 2, name: 'AgendaChiTiet.docx', category: 'Agenda', type: 'DOCX', size: '860 KB', uploader: 'Trần Thị B', uploadDate: '09/07/2026', updatedAt: '14/07/2026', version: 'v1.4', description: 'Lịch trình chi tiết theo từng nội dung họp.', note: 'Bổ sung thời lượng phát biểu.' },
  { id: 3, name: 'PhieuDangKyNoiDung.pdf', category: 'Agenda', type: 'PDF', size: '540 KB', uploader: 'Phạm Văn C', uploadDate: '08/07/2026', updatedAt: '11/07/2026', version: 'v1.1', description: 'Phiếu đăng ký nội dung trình bày tại cuộc họp.', note: 'Mẫu dùng nội bộ.' },
  { id: 4, name: 'QuyetDinh01.pdf', category: 'Quyết định', type: 'PDF', size: '2.4 MB', uploader: 'Nguyễn Văn A', uploadDate: '10/07/2026', updatedAt: '13/07/2026', version: 'v1.0', description: 'Quyết định triệu tập cuộc họp giao ban.', note: 'Bản ký số.' },
  { id: 5, name: 'QuyetDinhPhanCong.pdf', category: 'Quyết định', type: 'PDF', size: '1.8 MB', uploader: 'Lê Thị D', uploadDate: '11/07/2026', updatedAt: '15/07/2026', version: 'v2.1', description: 'Quyết định phân công nhiệm vụ sau cuộc họp.', note: 'Chờ rà soát lần cuối.' },
  { id: 6, name: 'QuyetDinhThanhLapToCongTac.docx', category: 'Quyết định', type: 'DOCX', size: '720 KB', uploader: 'Hoàng Văn E', uploadDate: '12/07/2026', updatedAt: '12/07/2026', version: 'v1.0', description: 'Dự thảo quyết định thành lập tổ công tác.', note: 'Dự thảo.' },
  { id: 7, name: 'BaoCaoTongHop.docx', category: 'Báo cáo', type: 'DOCX', size: '3.1 MB', uploader: 'Trần Thị B', uploadDate: '09/07/2026', updatedAt: '15/07/2026', version: 'v2.0', description: 'Báo cáo tổng hợp tình hình thực hiện nhiệm vụ tháng 07.', note: 'Đã nhập số liệu mới.' },
  { id: 8, name: 'BaoCaoTaiChinh.xlsx', category: 'Báo cáo', type: 'XLSX', size: '2.7 MB', uploader: 'Phạm Văn C', uploadDate: '10/07/2026', updatedAt: '14/07/2026', version: 'v1.3', description: 'Bảng tổng hợp kinh phí phục vụ nhiệm vụ trọng tâm.', note: 'Kiểm tra lại cột dự toán.' },
  { id: 9, name: 'BaoCaoNhanSu.pdf', category: 'Báo cáo', type: 'PDF', size: '1.9 MB', uploader: 'Lê Thị D', uploadDate: '11/07/2026', updatedAt: '15/07/2026', version: 'v1.2', description: 'Báo cáo tình hình nhân sự và phân công trực ban.', note: 'Bổ sung phụ lục.' },
  { id: 10, name: 'BaoCaoTienDoDuAn.xlsx', category: 'Báo cáo', type: 'XLSX', size: '4.5 MB', uploader: 'Hoàng Văn E', uploadDate: '12/07/2026', updatedAt: '15/07/2026', version: 'v2.2', description: 'Theo dõi tiến độ các dự án đang triển khai trên địa bàn.', note: 'Có biểu đồ tổng hợp.' },
  { id: 11, name: 'BaoCaoAnNinh.docx', category: 'Báo cáo', type: 'DOCX', size: '1.4 MB', uploader: 'Vũ Thị F', uploadDate: '12/07/2026', updatedAt: '13/07/2026', version: 'v1.0', description: 'Báo cáo công tác an ninh trật tự.', note: 'Gửi kèm phụ lục riêng.' },
  { id: 12, name: 'TrinhChieu.pptx', category: 'PowerPoint', type: 'PPTX', size: '8.6 MB', uploader: 'Nguyễn Văn A', uploadDate: '13/07/2026', updatedAt: '15/07/2026', version: 'v2.0', description: 'Slide trình chiếu nội dung trọng tâm cuộc họp.', note: 'Đã tối ưu hình ảnh.' },
  { id: 13, name: 'TrinhChieuTaiChinh.pptx', category: 'PowerPoint', type: 'PPTX', size: '6.2 MB', uploader: 'Phạm Văn C', uploadDate: '13/07/2026', updatedAt: '14/07/2026', version: 'v1.5', description: 'Slide trình bày báo cáo tài chính.', note: 'Đợi duyệt số liệu.' },
  { id: 14, name: 'BanDoTienDo.png', category: 'PowerPoint', type: 'PNG', size: '980 KB', uploader: 'Vũ Thị F', uploadDate: '13/07/2026', updatedAt: '13/07/2026', version: 'v1.0', description: 'Hình ảnh minh họa tiến độ dự án dùng trong slide.', note: 'Độ phân giải cao.' },
  { id: 15, name: 'BienBanHop.docx', category: 'Biên bản', type: 'DOCX', size: '1.6 MB', uploader: 'Trần Thị B', uploadDate: '15/07/2026', updatedAt: '15/07/2026', version: 'v1.0', description: 'Biên bản cuộc họp giao ban UBND xã.', note: 'Bản nháp sau họp.' },
  { id: 16, name: 'BienBanKetLuan.pdf', category: 'Biên bản', type: 'PDF', size: '2.1 MB', uploader: 'Lê Thị D', uploadDate: '15/07/2026', updatedAt: '16/07/2026', version: 'v1.1', description: 'Biên bản kết luận nội dung cuộc họp.', note: 'Cần ký xác nhận.' },
  { id: 17, name: 'PhieuLayYKien.docx', category: 'Biên bản', type: 'DOCX', size: '650 KB', uploader: 'Hoàng Văn E', uploadDate: '14/07/2026', updatedAt: '15/07/2026', version: 'v1.2', description: 'Phiếu lấy ý kiến đại biểu tham dự.', note: 'Mẫu tổng hợp.' },
  { id: 18, name: 'VideoHop.mp4', category: 'Video', type: 'MP4', size: '245 MB', uploader: 'Nguyễn Văn A', uploadDate: '15/07/2026', updatedAt: '15/07/2026', version: 'v1.0', description: 'Video ghi lại toàn bộ cuộc họp.', note: 'Lưu trữ nội bộ.' },
  { id: 19, name: 'VideoTomTat.mp4', category: 'Video', type: 'MP4', size: '62 MB', uploader: 'Vũ Thị F', uploadDate: '16/07/2026', updatedAt: '16/07/2026', version: 'v1.0', description: 'Video tóm tắt các nội dung chính.', note: 'Dùng cho báo cáo nhanh.' },
  { id: 20, name: 'HinhAnhHoiTruong.jpg', category: 'Video', type: 'JPG', size: '3.3 MB', uploader: 'Trần Thị B', uploadDate: '15/07/2026', updatedAt: '15/07/2026', version: 'v1.0', description: 'Ảnh toàn cảnh hội trường trong cuộc họp.', note: 'Dùng cho tin nội bộ.' },
  { id: 21, name: 'DanhSachDaiBieu.xlsx', category: 'Khác', type: 'XLSX', size: '780 KB', uploader: 'Lê Thị D', uploadDate: '09/07/2026', updatedAt: '14/07/2026', version: 'v1.6', description: 'Danh sách đại biểu tham dự cuộc họp.', note: 'Có thông tin liên hệ.' },
  { id: 22, name: 'PhuLucSoLieu.zip', category: 'Khác', type: 'ZIP', size: '12.4 MB', uploader: 'Phạm Văn C', uploadDate: '12/07/2026', updatedAt: '15/07/2026', version: 'v2.0', description: 'Tệp nén phụ lục số liệu chi tiết.', note: 'Bao gồm bảng Excel và hình ảnh.' },
  { id: 23, name: 'MauBieuKiemTra.docx', category: 'Khác', type: 'DOCX', size: '910 KB', uploader: 'Hoàng Văn E', uploadDate: '12/07/2026', updatedAt: '12/07/2026', version: 'v1.0', description: 'Mẫu biểu kiểm tra tiến độ sau cuộc họp.', note: 'Biểu mẫu dùng chung.' },
  { id: 24, name: 'ThongBaoKetLuan.pdf', category: 'Khác', type: 'PDF', size: '1.1 MB', uploader: 'Nguyễn Văn A', uploadDate: '16/07/2026', updatedAt: '16/07/2026', version: 'v1.0', description: 'Thông báo kết luận sau cuộc họp.', note: 'Gửi các bộ phận liên quan.' },
  { id: 25, name: 'AnhMinhHoaNoiDung.png', category: 'Khác', type: 'PNG', size: '1.7 MB', uploader: 'Vũ Thị F', uploadDate: '14/07/2026', updatedAt: '15/07/2026', version: 'v1.1', description: 'Ảnh minh họa cho tài liệu tổng hợp.', note: 'Đã nén dung lượng.' },
]
