export const meetingMinutesData = {
  meeting: {
    title: 'Họp giao ban UBND phường tháng 07/2026',
    time: '08:00 - 10:30, Thứ Sáu, 17/07/2026',
    room: 'Phòng họp trực tuyến số 01',
    chairperson: 'Ông Nguyễn Văn Minh - Chủ tịch UBND phường',
    secretary: 'Bà Trần Thị Lan - Văn phòng HĐND và UBND',
  },
  contents: [
    {
      id: 1,
      title: 'Đánh giá tình hình kinh tế - xã hội tháng 07',
      content: 'Các đơn vị báo cáo tiến độ thực hiện chỉ tiêu kinh tế - xã hội, công tác an sinh, trật tự đô thị và các nhiệm vụ trọng tâm trong tháng.',
    },
    {
      id: 2,
      title: 'Công tác cải cách hành chính',
      content: 'Bộ phận một cửa trình bày kết quả tiếp nhận, giải quyết hồ sơ trực tuyến, tỷ lệ đúng hạn và các vướng mắc cần xử lý trong tuần tới.',
    },
    {
      id: 3,
      title: 'Kế hoạch chuyển đổi số cấp phường',
      content: 'Thảo luận việc cập nhật dữ liệu dân cư, triển khai chữ ký số nội bộ và chuẩn hóa quy trình xử lý văn bản điện tử.',
    },
    {
      id: 4,
      title: 'Công tác phòng chống thiên tai',
      content: 'Rà soát phương án trực ban, danh sách điểm xung yếu, vật tư dự phòng và kênh thông tin cảnh báo đến các tổ dân phố.',
    },
    {
      id: 5,
      title: 'Tổ chức các hoạt động cộng đồng',
      content: 'Các đoàn thể báo cáo kế hoạch phối hợp tuyên truyền vệ sinh môi trường, chỉnh trang tuyến phố và hỗ trợ hộ gia đình chính sách.',
    },
  ],
  opinions: [
    {
      id: 1,
      speaker: 'Ông Phạm Quốc Huy',
      position: 'Trưởng Công an phường',
      content: 'Đề nghị tăng cường phối hợp kiểm tra an ninh trật tự tại các khu vực chợ tạm vào khung giờ cao điểm.',
    },
    {
      id: 2,
      speaker: 'Bà Lê Thu Hà',
      position: 'Công chức Tư pháp - Hộ tịch',
      content: 'Cần bổ sung hướng dẫn cho người dân khi nộp hồ sơ trực tuyến để giảm số hồ sơ phải bổ sung nhiều lần.',
    },
    {
      id: 3,
      speaker: 'Ông Võ Minh Đức',
      position: 'Công chức Địa chính - Xây dựng',
      content: 'Đề xuất cập nhật bản đồ các điểm ngập cục bộ để phục vụ phương án ứng phó mưa lớn trong tháng tới.',
    },
    {
      id: 4,
      speaker: 'Bà Nguyễn Thị Mai',
      position: 'Chủ tịch Hội Liên hiệp Phụ nữ',
      content: 'Hội sẽ phối hợp vận động hội viên tham gia ngày chủ nhật xanh và hỗ trợ truyền thông về phân loại rác tại nguồn.',
    },
    {
      id: 5,
      speaker: 'Ông Trần Anh Tuấn',
      position: 'Bí thư Đoàn phường',
      content: 'Đoàn thanh niên đăng ký phụ trách nhóm hỗ trợ người cao tuổi sử dụng dịch vụ công trực tuyến.',
    },
    {
      id: 6,
      speaker: 'Bà Phạm Thị Kim Ngân',
      position: 'Công chức Văn hóa - Xã hội',
      content: 'Cần thống nhất lịch kiểm tra các điểm sinh hoạt văn hóa cộng đồng để tránh trùng với hoạt động của tổ dân phố.',
    },
    {
      id: 7,
      speaker: 'Ông Đỗ Hoàng Nam',
      position: 'Tổ trưởng Tổ dân phố 05',
      content: 'Kiến nghị sớm sửa hệ thống chiếu sáng tại tuyến đường nội bộ để bảo đảm an toàn đi lại ban đêm.',
    },
    {
      id: 8,
      speaker: 'Bà Huỳnh Ngọc Ánh',
      position: 'Kế toán ngân sách',
      content: 'Đề nghị các bộ phận gửi dự toán chi tiết trước ngày 22/07 để tổng hợp trình lãnh đạo phê duyệt.',
    },
  ],
  conclusions: [
    'Các bộ phận tiếp tục bám sát kế hoạch tháng 07, ưu tiên giải quyết các nhiệm vụ còn chậm tiến độ.',
    'Bộ phận một cửa hoàn thiện tài liệu hướng dẫn nộp hồ sơ trực tuyến, công bố trên cổng thông tin phường.',
    'Công an phường phối hợp tổ dân phố tăng cường kiểm tra trật tự đô thị tại các khu vực trọng điểm.',
    'Văn phòng UBND tổng hợp nhiệm vụ sau họp và theo dõi tiến độ thực hiện hằng tuần.',
  ],
  tasks: [
    {
      id: 1,
      content: 'Hoàn thiện báo cáo tình hình kinh tế - xã hội tháng 07',
      assignee: 'Bà Trần Thị Lan',
      unit: 'Văn phòng UBND',
      dueDate: '20/07/2026',
      status: 'Đang thực hiện',
    },
    {
      id: 2,
      content: 'Cập nhật hướng dẫn nộp hồ sơ dịch vụ công trực tuyến',
      assignee: 'Bà Lê Thu Hà',
      unit: 'Tư pháp - Hộ tịch',
      dueDate: '21/07/2026',
      status: 'Chưa bắt đầu',
    },
    {
      id: 3,
      content: 'Rà soát các điểm ngập và vật tư phòng chống thiên tai',
      assignee: 'Ông Võ Minh Đức',
      unit: 'Địa chính - Xây dựng',
      dueDate: '23/07/2026',
      status: 'Đang thực hiện',
    },
    {
      id: 4,
      content: 'Lập kế hoạch hỗ trợ người dân sử dụng dịch vụ công',
      assignee: 'Ông Trần Anh Tuấn',
      unit: 'Đoàn Thanh niên',
      dueDate: '24/07/2026',
      status: 'Chưa bắt đầu',
    },
    {
      id: 5,
      content: 'Kiểm tra hệ thống chiếu sáng tuyến đường nội bộ',
      assignee: 'Ông Đỗ Hoàng Nam',
      unit: 'Tổ dân phố 05',
      dueDate: '25/07/2026',
      status: 'Chờ phối hợp',
    },
    {
      id: 6,
      content: 'Tổng hợp dự toán phục vụ các hoạt động cộng đồng',
      assignee: 'Bà Huỳnh Ngọc Ánh',
      unit: 'Tài chính - Kế toán',
      dueDate: '22/07/2026',
      status: 'Đang thực hiện',
    },
  ],
}
