export const userRoles = [
  'Tất cả người dùng',
  'Quản trị hệ thống',
  'Lãnh đạo',
  'Thư ký',
  'Trưởng phòng/Ban',
  'Thành viên',
]

export const userDepartments = [
  'Văn phòng HĐND và UBND',
  'Lãnh đạo UBND',
  'Công an phường',
  'Tư pháp - Hộ tịch',
  'Địa chính - Xây dựng',
  'Văn hóa - Xã hội',
  'Tài chính - Kế toán',
  'Đoàn Thanh niên',
]

export const userStatuses = ['Đang hoạt động', 'Bị khóa', 'Chờ kích hoạt']

export const rolePermissions = {
  'Quản trị hệ thống': [
    'Quản lý tài khoản',
    'Quản lý phòng họp',
    'Quản lý thiết bị',
    'Quản lý phân quyền',
    'Cấu hình hệ thống',
    'Xem toàn bộ báo cáo',
  ],
  'Lãnh đạo': [
    'Tạo lịch họp',
    'Phê duyệt lịch họp',
    'Chủ trì cuộc họp',
    'Xem báo cáo tổng hợp',
    'Xem biên bản',
    'Theo dõi nhiệm vụ',
  ],
  'Thư ký': [
    'Chuẩn bị nội dung cuộc họp',
    'Quản lý tài liệu',
    'Điều hành phiên họp',
    'Ghi biên bản trực tiếp',
    'Theo dõi biểu quyết',
    'Xuất biên bản Word',
    'Xuất biên bản PDF',
  ],
  'Trưởng phòng/Ban': [
    'Quản lý cuộc họp của đơn vị',
    'Xem lịch họp',
    'Quản lý tài liệu đơn vị',
    'Theo dõi nhiệm vụ được giao',
    'Xem kết luận cuộc họp',
  ],
  'Thành viên': [
    'Nhận thông báo họp',
    'Điểm danh bằng khuôn mặt',
    'Xem tài liệu',
    'Tham gia cuộc họp',
    'Tham gia biểu quyết',
    'Theo dõi kết luận',
    'Theo dõi nhiệm vụ',
  ],
}

export const usersData = [
  {
    id: 1,
    name: 'Nguyễn Văn Minh',
    title: 'Chủ tịch UBND phường',
    department: 'Lãnh đạo UBND',
    role: 'Lãnh đạo',
    email: 'minhnv@phuongxa.gov.vn',
    phone: '0901 234 001',
    status: 'Đang hoạt động',
    avatar: 'NM',
    createdAt: '02/01/2026',
    lastLogin: '18/07/2026 08:12',
  },
  {
    id: 2,
    name: 'Trần Thị Lan',
    title: 'Chánh Văn phòng',
    department: 'Văn phòng HĐND và UBND',
    role: 'Thư ký',
    email: 'lantt@phuongxa.gov.vn',
    phone: '0901 234 002',
    status: 'Đang hoạt động',
    avatar: 'TL',
    createdAt: '05/01/2026',
    lastLogin: '18/07/2026 09:01',
  },
  {
    id: 3,
    name: 'Phạm Quốc Huy',
    title: 'Trưởng Công an phường',
    department: 'Công an phường',
    role: 'Trưởng phòng/Ban',
    email: 'huypq@phuongxa.gov.vn',
    phone: '0901 234 003',
    status: 'Đang hoạt động',
    avatar: 'PH',
    createdAt: '08/01/2026',
    lastLogin: '17/07/2026 16:45',
  },
  {
    id: 4,
    name: 'Lê Thu Hà',
    title: 'Công chức Tư pháp - Hộ tịch',
    department: 'Tư pháp - Hộ tịch',
    role: 'Thành viên',
    email: 'halt@phuongxa.gov.vn',
    phone: '0901 234 004',
    status: 'Đang hoạt động',
    avatar: 'LH',
    createdAt: '11/01/2026',
    lastLogin: '18/07/2026 07:58',
  },
  {
    id: 5,
    name: 'Võ Minh Đức',
    title: 'Công chức Địa chính - Xây dựng',
    department: 'Địa chính - Xây dựng',
    role: 'Trưởng phòng/Ban',
    email: 'ducvm@phuongxa.gov.vn',
    phone: '0901 234 005',
    status: 'Chờ kích hoạt',
    avatar: 'VD',
    createdAt: '15/01/2026',
    lastLogin: 'Chưa đăng nhập',
  },
  {
    id: 6,
    name: 'Nguyễn Thị Mai',
    title: 'Chủ tịch Hội Liên hiệp Phụ nữ',
    department: 'Văn hóa - Xã hội',
    role: 'Thành viên',
    email: 'maint@phuongxa.gov.vn',
    phone: '0901 234 006',
    status: 'Đang hoạt động',
    avatar: 'NM',
    createdAt: '18/01/2026',
    lastLogin: '16/07/2026 14:22',
  },
  {
    id: 7,
    name: 'Trần Anh Tuấn',
    title: 'Bí thư Đoàn phường',
    department: 'Đoàn Thanh niên',
    role: 'Thành viên',
    email: 'tuanta@phuongxa.gov.vn',
    phone: '0901 234 007',
    status: 'Đang hoạt động',
    avatar: 'TT',
    createdAt: '20/01/2026',
    lastLogin: '18/07/2026 08:31',
  },
  {
    id: 8,
    name: 'Phạm Thị Kim Ngân',
    title: 'Công chức Văn hóa - Xã hội',
    department: 'Văn hóa - Xã hội',
    role: 'Thư ký',
    email: 'nganptk@phuongxa.gov.vn',
    phone: '0901 234 008',
    status: 'Đang hoạt động',
    avatar: 'PN',
    createdAt: '23/01/2026',
    lastLogin: '17/07/2026 10:05',
  },
  {
    id: 9,
    name: 'Đỗ Hoàng Nam',
    title: 'Tổ trưởng Tổ dân phố 05',
    department: 'Văn phòng HĐND và UBND',
    role: 'Thành viên',
    email: 'namdh@phuongxa.gov.vn',
    phone: '0901 234 009',
    status: 'Bị khóa',
    avatar: 'DN',
    createdAt: '25/01/2026',
    lastLogin: '04/07/2026 11:19',
  },
  {
    id: 10,
    name: 'Huỳnh Ngọc Ánh',
    title: 'Kế toán ngân sách',
    department: 'Tài chính - Kế toán',
    role: 'Trưởng phòng/Ban',
    email: 'anhhn@phuongxa.gov.vn',
    phone: '0901 234 010',
    status: 'Đang hoạt động',
    avatar: 'HA',
    createdAt: '28/01/2026',
    lastLogin: '18/07/2026 08:44',
  },
  {
    id: 11,
    name: 'Bùi Quang Khải',
    title: 'Cán bộ Công nghệ thông tin',
    department: 'Văn phòng HĐND và UBND',
    role: 'Quản trị hệ thống',
    email: 'khaibq@phuongxa.gov.vn',
    phone: '0901 234 011',
    status: 'Đang hoạt động',
    avatar: 'BK',
    createdAt: '01/02/2026',
    lastLogin: '18/07/2026 09:20',
  },
  {
    id: 12,
    name: 'Lê Hoàng Phúc',
    title: 'Phó Chủ tịch UBND phường',
    department: 'Lãnh đạo UBND',
    role: 'Lãnh đạo',
    email: 'phuclh@phuongxa.gov.vn',
    phone: '0901 234 012',
    status: 'Đang hoạt động',
    avatar: 'LP',
    createdAt: '03/02/2026',
    lastLogin: '18/07/2026 07:35',
  },
]
